name: Run Tests and Notify Slack

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Worked'
          SLACK_TITLE: Github Actions
          SLACK_USERNAME: Cathy
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
